# https://taskfile.dev

version: '3'

vars:
  JAR: javakit-0.0.1-shaded.jar
  JAVAARGS: --enable-native-access=ALL-UNNAMED
  ENTRYPOINT: javakit.Main

tasks:
  build:
    cmds:
      - ./mvnw clean package
    silent: false
  execute:
    dir: target
    cmds:
      - java {{.JAVAARGS}} -jar {{.JAR}} {{.ENTRYPOINT}}
    silent: false
  run:
    deps: [build]
    dir: target
    cmds:
      - java {{.JAVAARGS}} -jar {{.JAR}} {{.ENTRYPOINT}}
    silent: false
